- name: Build and push
  id: build
  uses: docker/build-push-action@v6
  with:
    context: .
    file: Dockerfile
    push: true
    tags: ghcr.io/yt-ali/n8n-docker-ffmpeg:latest
    no-cache: true
- name: Output digest
  run: echo "Digest: ${{ steps.build.outputs.digest }}"
